import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-[100vh] w-[100vw] bg-gradient-to-r from-gray-600 via-[5B0662] to-[85F900] overflow-hidden">
      <body className="h-[100vh] w-[100vw] bg-gradient-to-r from-gray-600 via-[5B0662] to-[85F900] overflow-hidden">{children}</body>
    </html>
  );
}
